version: '3'
services:
  db:
    image: postgres:13.2-alpine
    environment: 
      - POSTGRES_PASSWORD=root1234
      - POSTGRES_DB=library
  web:
    build:
      context: client
      args: 
        - API_BASE_URL=http://localhost:3000/api/v1
    image: library-web
    ports:
      - "5000:5000"
  server:
    build: server
    image: library-server
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=root1234
      - DB_NAME=library
      - COOKIE_SECRET=library
    ports:
      - "3000:3000"
      
